### ISSUE TITLE
엔티티 1차 설계 완성, API 요구사항 정의

### ISSUE THREAD

**Issue by DevCHW** [DevCHW/justshop-server#13]
## 📝 요약
데이터베이스 테이블에 대하여 엔티티 관계도를 1차적으로 정의한 뒤, 추후 수정해나가며 개발하기
설계된 엔티티를 바탕으로 기능을 정의하여 빠르게 요구사항대로 RestDocs 문서 작성

## 💡 Todo
- [ ] 데이터베이스 테이블 설계를 마무리한다.
- [ ] 설계된 테이블을 바탕으로 엔티티 생성
- [ ] 요구사항 기능 정의
- [ ] API 스펙 정의하여 Rest Docs 작성

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
